### ISSUE TITLE
Implementation and suggestions

### ISSUE THREAD

**Issue by gsabater** [mistermantas/hop-on-discord#2]
Hello Mantas!

Nice plugin you have here, I have found it very useful and well done, and in fact I have already implemented it in my website at https://steam-backlog.com 

I would like to say a few things that I have found while the implementation:

- While the plugin is easy to implement, there is no references about installation either in the documentation or on the demo site. I'd suggest to add a few lines of text telling to copy the code found in the snippet file.

- There is a script on the top of the snippet, but that script is not needed at all with the inline onclick events.

- I wanted to make the FAB bigger, and found that the discord icon wasn't centering well, so I have used display flex to fix this and have the icon always centered regardless of the FAB size. Also I would use bottom and right to position the button instead of margins. Those are my changes:
```css
.discord-button {
    ...
    display: flex;
    text-align: center;
    align-items: center;
    justify-content: center;
    position: fixed;
    bottom: 25px;
    right: 25px;
    width: 70px;
    height: 70px;
    ...
}
.discord-button svg {
    height: 75%;
    ...
}
```

- Even in the dark layout, the FAB and the icon weren't very dark, I have updated the style as well for dark mode:
```css
.discord-button {
    ...
    background: #483c8b;
    ...
}
.discord-button svg path {
    fill: white;
}
```

- Finally I have removed the margin top on the `.discord-dialog__guild-icon` element

I have made a few more changes like the button size, and the dialog width, but those were personal preferences.

Finally, tell you that I haven't been able to see the FAB on https://eggylyte.com/ even when you say so on the documentation and the site.

Congratulation on the plugin.
